
export interface PolymarketTrade {
  proxyWallet: string;
  side: string;
  asset: string;
  conditionId: string;
  size: number;
  price: number;
  timestamp: number;
  title: string;
  slug: string;
  icon: string;
  eventSlug: string;
  outcome: string;
  outcomeIndex: number;
  name: string;
  pseudonym: string;
  bio: string;
  profileImage: string;
  profileImageOptimized: string;
  transactionHash: string;
}

export interface UserPosition {
  proxyWallet: string;
  asset: string;
  conditionId: string;
  size: number;
  avgPrice: number;
  initialValue: number;
  currentValue: number;
  cashPnl: number;
  percentPnl: number;
  totalBought: number;
  realizedPnl: number;
  percentRealizedPnl: number;
  curPrice: number;
  redeemable: boolean;
  mergeable: boolean;
  title: string;
  slug: string;
  icon: string;
  eventSlug: string;
  outcome: string;
  outcomeIndex: number;
  oppositeOutcome: string;
  oppositeAsset: string;
  endDate: string;
  negativeRisk: boolean;
}

export interface MarketInfo {
  id: string;
  question: string;
  conditionId: string;
  slug: string;
  resolutionSource: string;
  endDate: string;
  startDate: string;
  image: string;
  icon: string;
  description: string;
  outcomes: string;
  outcomePrices: string;
  volume: string;
  active: boolean;
  closed: boolean;
  marketMakerAddress: string;
  createdAt: string;
  updatedAt: string;
  closedTime: string;
  umaResolutionStatus: string;
  volumeNum: number;
  endDateIso: string;
  startDateIso: string;
  hasReviewedDates: boolean;
  volume24hr: number;
  volume1wk: number;
  volume1mo: number;
  volume1yr: number;
  clobTokenIds: string;
  volume24hrClob: number;
  volume1wkClob: number;
  volume1moClob: number;
  volume1yrClob: number;
  volumeClob: string;
  acceptingOrders: boolean;
  approved: boolean;
}


// // export interface PolymarketTrade {
// //   proxyWallet: string;
// //   timestamp: number;
// //   conditionId: string;
// //   type: string;
// //   size: number;
// //   usdcSize: number;
// //   transactionHash: string;
// //   price: number;
// //   asset: string;
// //   side: string;
// //   outcomeIndex: number;
// //   title: string;
// //   slug: string;
// //   icon: string;
// //   eventSlug: string;
// //   outcome: string;
// //   name: string;
// //   pseudonym: string;
// //   bio: string;
// //   profileImage: string;
// //   profileImageOptimized: string;
// }

// export interface ImageOptimized {
//     id: string;
//     imageUrlSource: string;
//     imageUrlOptimized: string;
//     imageSizeKbSource: number;
//     imageSizeKbOptimized: number;
//     imageOptimizedComplete: boolean;
//     imageOptimizedLastUpdated: string;
//     relID: number;
//     field: string;
//     relname: string;
// }

// export interface Tag {
//     id: string;
//     label: string;
//     slug: string;
//     forceShow: boolean;
//     publishedAt: string;
//     createdBy: number;
//     updatedBy: number;
//     createdAt: string;
//     updatedAt: string;
//     forceHide: boolean;
//     isCarousel: boolean;
// }

// export interface Category {
//     id: string;
//     label: string;
//     parentCategory: string;
//     slug: string;
//     publishedAt: string;
//     createdBy: string;
//     updatedBy: string;
//     createdAt: string;
//     updatedAt: string;
// }

// export interface Chat {
//     id: string;
//     channelId: string;
//     channelName: string;
//     channelImage: string;
//     live: boolean;
//     startTime: string;
//     endTime: string;
// }

// export interface EventCreator {
//     id: string;
//     creatorName: string;
//     creatorUrl: string;
//     creatorImage: string;
//     createdAt: string;
//     updatedAt: string;
// }

// export interface Template {
//     id: string;
//     eventTitle: string;
//     eventSlug: string;
//     eventImage: string;
//     marketTitle: string;
//     description: string;
//     resolutionSource: string;
//     negRisk: boolean;
//     sortBy: string;
//     showMarketImages: boolean;
//     seriesSlug: string;
//     outcomes: string;
// }

// export interface MarketInfo {
//     id: string;
//     question: string;
//     conditionId: string;
//     slug: string;
//     twitterCardImage: string;
//     resolutionSource: string;
//     endDate: string;
//     category: string;
//     ammType: string;
//     liquidity: string;
//     sponsorName: string;
//     sponsorImage: string;
//     startDate: string;
//     xAxisValue: string;
//     yAxisValue: string;
//     denominationToken: string;
//     fee: string;
//     image: string;
//     icon: string;
//     lowerBound: string;
//     upperBound: string;
//     description: string;
//     outcomes: string;
//     outcomePrices: string;
//     volume: string;
//     active: boolean;
//     marketType: string;
//     formatType: string;
//     lowerBoundDate: string;
//     upperBoundDate: string;
//     closed: boolean;
//     marketMakerAddress: string;
//     createdBy: number;
//     updatedBy: number;
//     createdAt: string;
//     updatedAt: string;
//     closedTime: string;
//     wideFormat: boolean;
//     new: boolean;
//     mailchimpTag: string;
//     featured: boolean;
//     archived: boolean;
//     resolvedBy: string;
//     restricted: boolean;
//     marketGroup: number;
//     groupItemTitle: string;
//     groupItemThreshold: string;
//     questionID: string;
//     umaEndDate: string;
//     enableOrderBook: boolean;
//     orderPriceMinTickSize: number;
//     orderMinSize: number;
//     umaResolutionStatus: string;
//     curationOrder: number;
//     volumeNum: number;
//     liquidityNum: number;
//     endDateIso: string;
//     startDateIso: string;
//     umaEndDateIso: string;
//     hasReviewedDates: boolean;
//     readyForCron: boolean;
//     commentsEnabled: boolean;
//     volume24hr: number;
//     volume1wk: number;
//     volume1mo: number;
//     volume1yr: number;
//     gameStartTime: string;
//     secondsDelay: number;
//     clobTokenIds: string;
//     disqusThread: string;
//     shortOutcomes: string;
//     teamAID: string;
//     teamBID: string;
//     umaBond: string;
//     umaReward: string;
//     fpmmLive: boolean;
//     volume24hrAmm: number;
//     volume1wkAmm: number;
//     volume1moAmm: number;
//     volume1yrAmm: number;
//     volume24hrClob: number;
//     volume1wkClob: number;
//     volume1moClob: number;
//     volume1yrClob: number;
//     volumeAmm: number;
//     volumeClob: number;
//     liquidityAmm: number;
//     liquidityClob: number;
//     makerBaseFee: number;
//     takerBaseFee: number;
//     customLiveness: number;
//     acceptingOrders: boolean;
//     notificationsEnabled: boolean;
//     score: number;
//     imageOptimized: ImageOptimized;
//     iconOptimized: ImageOptimized;
//     events: Array<Event>;  // Need to define Event
//     categories: Array<Category>;
//     tags: Array<Tag>;
//     creator: string;
//     ready: boolean;
//     funded: boolean;
//     pastSlugs: string;
//     readyTimestamp: string;
//     fundedTimestamp: string;
//     acceptingOrdersTimestamp: string;
//     competitive: number;
//     rewardsMinSize: number;
//     rewardsMaxSpread: number;
//     spread: number;
//     automaticallyResolved: boolean;
//     oneDayPriceChange: number;
//     oneHourPriceChange: number;
//     oneWeekPriceChange: number;
//     oneMonthPriceChange: number;
//     oneYearPriceChange: number;
//     lastTradePrice: number;
//     bestBid: number;
//     bestAsk: number;
//     automaticallyActive: boolean;
//     clearBookOnStart: boolean;
//     chartColor: string;
//     seriesColor: string;
//     showGmpSeries: boolean;
//     showGmpOutcome: boolean;
//     manualActivation: boolean;
//     negRiskOther: boolean;
//     gameId: string;
//     groupItemRange: string;
//     sportsMarketType: string;
//     line: number;
//     umaResolutionStatuses: string;
//     pendingDeployment: boolean;
//     deploying: boolean;
//     deployingTimestamp: string;
//     scheduledDeploymentTimestamp: string;
//     rfqEnabled: boolean;
//     eventStartTime: string;
// }

// export interface Event {
//     id: string;
//     ticker: string;
//     slug: string;
//     title: string;
//     subtitle: string;
//     description: string;
//     resolutionSource: string;
//     startDate: string;
//     creationDate: string;
//     endDate: string;
//     image: string;
//     icon: string;
//     active: boolean;
//     closed: boolean;
//     archived: boolean;
//     new: boolean;
//     featured: boolean;
//     restricted: boolean;
//     liquidity: number;
//     volume: number;
//     openInterest: number;
//     sortBy: string;
//     category: string;
//     subcategory: string;
//     isTemplate: boolean;
//     templateVariables: string;
//     published_at: string;
//     createdBy: string;
//     updatedBy: string;
//     createdAt: string;
//     updatedAt: string;
//     commentsEnabled: boolean;
//     competitive: number;
//     volume24hr: number;
//     volume1wk: number;
//     volume1mo: number;
//     volume1yr: number;
//     featuredImage: string;
//     disqusThread: string;
//     parentEvent: string;
//     enableOrderBook: boolean;
//     liquidityAmm: number;
//     liquidityClob: number;
//     negRisk: boolean;
//     negRiskMarketID: string;
//     negRiskFeeBips: number;
//     commentCount: number;
//     imageOptimized: ImageOptimized;
//     iconOptimized: ImageOptimized;
//     featuredImageOptimized: ImageOptimized;
//     subEvents: Array<string>;
//     markets: Array<any>;  // Need to define Market, but recursive, so any for now
//     series: Array<Series>;  // Need to define Series
//     categories: Array<Category>;
//     collections: Array<any>;  // Complex, use any
//     tags: Array<Tag>;
//     cyom: boolean;
//     closedTime: string;
//     showAllOutcomes: boolean;
//     showMarketImages: boolean;
//     automaticallyResolved: boolean;
//     enableNegRisk: boolean;
//     automaticallyActive: boolean;
//     eventDate: string;
//     startTime: string;
//     eventWeek: number;
//     seriesSlug: string;
//     score: string;
//     elapsed: string;
//     period: string;
//     live: boolean;
//     ended: boolean;
//     finishedTimestamp: string;
//     gmpChartMode: string;
//     eventCreators: Array<EventCreator>;
//     tweetCount: number;
//     chats: Array<Chat>;
//     featuredOrder: number;
//     estimateValue: boolean;
//     cantEstimate: boolean;
//     estimatedValue: string;
//     templates: Array<Template>;
//     spreadsMainLine: number;
//     totalsMainLine: number;
//     carouselMap: string;
//     pendingDeployment: boolean;
//     deploying: boolean;
//     deployingTimestamp: string;
//     scheduledDeploymentTimestamp: string;
//     gameStatus: string;
// }

// export interface Series {
//     id: string;
//     ticker: string;
//     slug: string;
//     title: string;
//     subtitle: string;
//     seriesType: string;
//     recurrence: string;
//     description: string;
//     image: string;
//     icon: string;
//     layout: string;
//     active: boolean;
//     closed: boolean;
//     archived: boolean;
//     new: boolean;
//     featured: boolean;
//     restricted: boolean;
//     isTemplate: boolean;
//     templateVariables: boolean;
//     publishedAt: string;
//     createdBy: string;
//     updatedBy: string;
//     createdAt: string;
//     updatedAt: string;
//     commentsEnabled: boolean;
//     competitive: string;
//     volume24hr: number;
//     volume: number;
//     liquidity: number;
//     startDate: string;
//     pythTokenID: string;
//     cgAssetName: string;
//     score: number;
//     events: Array<any>;  // Recursive, use any
//     collections: Array<any>;
//     categories: Array<Category>;
//     tags: Array<Tag>;
//     commentCount: number;
//     chats: Array<Chat>;
// }
